# Generated by Django 5.2.5 on 2025-09-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
