# Generated by Django 5.2.5 on 2025-09-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_create_admin'),
        ('inventory', '0009_alter_productimage_image'),
    ]

    operations = [
    ]
